"""initial metadata schema

Revision ID: 09a9712f5623
Revises: 
Create Date: 2026-01-30 12:47:10.014177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a9712f5623'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshot',
    sa.Column('snapshot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('schema_snapshot',
    sa.Column('schema_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('schema_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.snapshot_id'], ),
    sa.PrimaryKeyConstraint('schema_id')
    )
    op.create_table('table_snapshot',
    sa.Column('table_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['schema_id'], ['schema_snapshot.schema_id'], ),
    sa.PrimaryKeyConstraint('table_id')
    )
    op.create_table('column_snapshot',
    sa.Column('column_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('nullable', sa.Boolean(), nullable=False),
    sa.Column('ordinal_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['table_snapshot.table_id'], ),
    sa.PrimaryKeyConstraint('column_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('column_snapshot')
    op.drop_table('table_snapshot')
    op.drop_table('schema_snapshot')
    op.drop_table('snapshot')
    # ### end Alembic commands ###
