# =====================================================================
# bump_version.ps1 — single-command version bump for SCION.
#
# Usage (from project root):
#   .\tools\bump_version.ps1 1.14.03 "short summary line"
#
# Updates two places that have to stay in sync:
#   1. frontend/src/lib/constants.ts — the runtime APP_VERSION constant
#      that drives the Sidebar footer and Home hero pill.
#   2. README.md — the "Version: BETA vX.Y.Z" header line + a new
#      changelog entry stub at the top of the Changelog section.
#
# What this script does NOT do:
#   - Commit the changes (git add/commit is up to you so you can edit
#     the changelog body before committing).
#   - Push or tag (those happen at PR-merge time).
#   - Validate the version format strictly — passes the string
#     through unchanged so RC tags like "1.14.0-rc1" work.
#
# Why we wrote this: every release we were touching constants.ts and
# README.md by hand, and forgetting the README half about 1 in 4
# releases. This file is the single source of truth for "what does
# 'bump version' mean."
# =====================================================================

param(
    [Parameter(Mandatory = $true, Position = 0)]
    [string]$Version,

    [Parameter(Mandatory = $true, Position = 1)]
    [string]$Summary
)

$ErrorActionPreference = "Stop"

# Resolve project root from this script's location so the tool works
# regardless of cwd. `tools/` is one level below root.
$root = Split-Path -Parent $PSScriptRoot
$constantsFile = Join-Path $root "frontend\src\lib\constants.ts"
$readmeFile    = Join-Path $root "README.md"

# Strip a leading `v` if the user passed one — we add it back ourselves
# everywhere it's needed, so accepting both forms makes the tool more
# forgiving without adding ambiguity.
$Version = $Version -replace '^v', ''
$tagged = "v$Version"

# Today's date in ISO format for the changelog entry header.
# UTC because that's what `release_policy.md` uses for tag timestamps;
# keeps changelog dates consistent regardless of who runs the script.
$today = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd")

# ──── 1. constants.ts ────
if (-not (Test-Path $constantsFile)) {
    throw "constants.ts not found at $constantsFile"
}
$constants = Get-Content $constantsFile -Raw -Encoding UTF8
$pattern = 'export const APP_VERSION = "v[^"]+";'
$replacement = "export const APP_VERSION = `"$tagged`";"
if ($constants -notmatch $pattern) {
    throw "Could not find APP_VERSION line in $constantsFile"
}
$constants = $constants -replace $pattern, $replacement
# `-NoNewline` because Set-Content otherwise appends one and the file
# would grow a blank line per bump. -Encoding utf8 (lowercase) writes
# without BOM on PS 7; on PS 5.1 it writes with BOM but Next.js
# tolerates either.
Set-Content -Path $constantsFile -Value $constants -NoNewline -Encoding utf8
Write-Host "  [OK] constants.ts -> $tagged" -ForegroundColor Green

# ──── 2. README.md header ────
if (-not (Test-Path $readmeFile)) {
    throw "README.md not found at $readmeFile"
}
$readme = Get-Content $readmeFile -Raw -Encoding UTF8
$headerPattern = '\*\*Version:\*\* BETA v[^\r\n]+'
$headerReplacement = "**Version:** BETA $tagged"
if ($readme -notmatch $headerPattern) {
    throw "Could not find Version header in $readmeFile"
}
$readme = $readme -replace $headerPattern, $headerReplacement
Write-Host "  [OK] README.md header -> $tagged" -ForegroundColor Green

# ──── 3. README.md changelog stub ────
# Inject a new entry at the top of the Changelog section. We anchor
# on the first existing `### v` line and prepend before it.
$stub = @"
### $tagged ($today) — $Summary

<!-- Fill in the body before committing. Stub auto-generated by tools/bump_version.ps1. -->


"@
$anchorPattern = '(?m)^### v\d'
$anchorMatch = [regex]::Match($readme, $anchorPattern)
if (-not $anchorMatch.Success) {
    throw "Could not find first changelog entry to anchor on. Insert one manually before re-running."
}
$readme = $readme.Substring(0, $anchorMatch.Index) + $stub + $readme.Substring($anchorMatch.Index)
Set-Content -Path $readmeFile -Value $readme -NoNewline -Encoding utf8
Write-Host "  [OK] README.md changelog stub inserted" -ForegroundColor Green

# ──── Done ────
Write-Host ""
Write-Host "Bumped to $tagged. Now:" -ForegroundColor Cyan
Write-Host "  1. Edit the changelog body in README.md (search for `"$tagged`")."
Write-Host "  2. git add -p frontend/src/lib/constants.ts README.md"
Write-Host "  3. git commit -m `"$tagged -- $Summary`""
